name: Execute SSH Commands

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "30 1,13 * * *"  # 每天早晚9点运行一次

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Get ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        # 从 GitHub Secrets 获取 ACCOUNTS_JSON 变量，并保存到文件 accounts.json

      - name: Generate SSH Commands
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          accounts=""
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')
            accounts="${accounts}${username}@${ssh}%0A"

            echo "echo \"Executing for $username@$ssh\"" >> sshpass.sh
            # echo "sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'bash <(curl -s https://raw.githubusercontent.com/gshtwy/socks5-hysteria2-for-serv00/main/crtest.sh)'" >> sshpass.sh
            echo "sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'bash <(curl -s https://raw.githubusercontent.com/ajsong/socks5-hysteria2-for-Serv00-CT8/main/crtest.sh)'" >> sshpass.sh
          done < <(jq -c '.[]' accounts.json)
          MESSAGE="Serv00 Check Cron%0A$accounts"
          TOKEN="$TG_TOKEN"
          CHAT_ID="$TG_CHAT_ID"
          URL="https://api.telegram.org/bot${TOKEN}/sendMessage"
          echo "curl -s -o /dev/null -X POST ${URL} -d chat_id=${CHAT_ID} -d text=\"${MESSAGE}\"" > sshpass.sh
          chmod +x sshpass.sh
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

      - name: Execute SSH Commands
        run: ./sshpass.sh
